services:
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    environment:
      - URLS= [ {url:'http://localhost:3000/api-docs/json',name:'Service1'},
        {url:'http://localhost:3010/api-docs/json',name:'Service2'}]
