name: Run Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install dependencies with yarn
        run: |
          corepack enable
          yarn install
      - name: Run test command
        run: yarn test
      - name: Run E2E test command
        run: yarn test:e2e
